# Generated by Django 6.0.2 on 2026-02-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('puesto', models.CharField(max_length=50)),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depa', models.CharField(choices=[('TI', 'Tecnologia de la informacion'), ('RRHH', 'Recursos Humanos'), ('Logistica', 'Logistica'), ('Ventas', 'Ventas'), ('Produccion', 'Produccion')], max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Empleados',
            },
        ),
    ]
