# Generated by Django 6.0.2 on 2026-02-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='depa',
            field=models.CharField(choices=[('TI', 'Tecnologia de la informacion'), ('RRHH', 'Recursos Humanos'), ('Logistica', 'Logistica'), ('Ventas', 'Ventas'), ('Produccion', 'Produccion')], max_length=50),
        ),
    ]
