# Generated by Django 5.2.7 on 2025-11-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinarias',
            fields=[
                ('id_veterinaria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'veterinarias',
            },
        ),
    ]
