# Generated by Django 5.2.7 on 2025-10-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('nivel', models.CharField(default='Basico', max_length=50)),
            ],
            options={
                'db_table': 'Perfil',
            },
        ),
    ]
