# Generated by Django 5.2.7 on 2025-11-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=55)),
                ('contacto', models.CharField(max_length=50)),
                ('id_veterinaria', models.IntegerField()),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
    ]
