# Generated by Django 5.2.7 on 2025-11-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responsables',
            fields=[
                ('id_responsable', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('contacto', models.CharField(max_length=50)),
                ('id_veterinaria', models.IntegerField()),
            ],
        ),
    ]
