# Generated by Django 5.2.7 on 2025-10-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('SuperHeroe', 'SuperHeroe'), ('Villano', 'Villano')], max_length=50)),
                ('habilidad', models.CharField(choices=[('Fuerza', 'Fuerza'), ('Velocidad', 'Velocidad'), ('Magia', 'Magia'), ('Inteligencia', 'Inteligencia')], max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Personajes',
            },
        ),
    ]
