# Generated by Django 6.0.2 on 2026-02-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('ocupacion', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'PERSONAS',
            },
        ),
    ]
