# Generated by Django 6.0.2 on 2026-02-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='tamaño',
            field=models.CharField(max_length=50),
        ),
    ]
