# Generated by Django 6.0.2 on 2026-02-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_mascota_tamaño'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='tamaño',
            field=models.CharField(db_column='tamaño', max_length=50),
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='tamaño',
            new_name='tamanio',
        ),
    ]
