# Generated by Django 6.0.2 on 2026-02-17 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='curo',
            new_name='curso',
        ),
    ]
