create table LIBROS_E (
	ISBN varchar(30) primary KEY,
    TITULO varchar (25),
    AUTOR varchar (30),
    AÑO_PUBLICADO INT,
    EDITORIAL VARCHAR(25),
    GENERO VARCHAR(25)
);
DROP table PRESTAMOS;
CREATE table USUARIO_E(
	ID_USUARIO INT primary KEY auto_increment,
    NOMBRE VARCHAR (20),
    APELLIDO VARCHAR(20),
    EMAIL VARCHAR(20) UNIQUE,
    TIPO ENUM("ESTUDIANTE","PROFESOR") NOT NULL
);

CREATE TABLE PRESTAMOS(
	ID_PRESTAMO INT primary KEY auto_increment,
    ISBN varchar(25),
    ID_USUARIO INT,
    FECHA_PRESTAMO DATE NOT NULL,
    FECHA_DEVOLUCION_ESPERADA DATE NOT NULL,
    FECHA_DEVOLUSION_REAL DATE,
    foreign key(ISBN) references LIBROS_E(ISBN),
    foreign key(ID_USUARIO) references USUARIO_E(ID_USUARIO),
    check (FECHA_DEVOLUCION_ESPERADA = date_add(FECHA_PRESTAMO, interval 15 DAY))
);

INSERT INTO LIBROS_E values("987-1", "DRACULA", "BRAM STOKER", 1982, "EDITORIAL 1", "TERROR"),
							("987-2", "CIEN AÑOS DE SOLEDAD", "GRABIEL GARCIA", 1972, "EDITORIAL 2", "NOVELA"),
                            ("987-3", "EL PRINCIPITO", "ANTONI", 1989, "EDITORIAL 3", "CUENTO"),
                            ("987-4", "ANGELES CAIDOS", "SUSAN EE", 1992, "EDITORIAL 4", "CIENCIA FICCION"),
                            ("987-5", "HISTORIAL DE TIEMPO", "STEPHEN", 2002, "EDITORIAL 5", "CIENCIA");
                            
INSERT INTO USUARIO_E (NOMBRE, APELLIDO, EMAIL, TIPO)
						values("JUAN", "PEREZ", "JUAN@gmail.com", "ESTUDIANTE"),
							("PEDRO", "SANCHEZ", "PEDRO@gmail.com","PROFESOR"),
                            ("MARIA", "LOPEZ", "Maria@.gamil.com", "ESTUDIANTE");		
                
                
select * FROM LIBROS_E;
                
select * FROM USUARIO_E;
                
-- vARIABLE TEMPORAL
SET @hoy = CURDATE();

-- SIGUE EN PRESTAMOS
INSERT PRESTAMOS(ISBN, ID_USUARIO, FECHA_PRESTAMO, FECHA_DEVOLUCION_ESPERADA) VALUES
			("987-1", 1, @hoy, date_add(@hoy, interval 15 DAY ) );
            
-- ENTREGADO CON RETRASO
INSERT PRESTAMOS(ISBN, ID_USUARIO, FECHA_PRESTAMO, FECHA_DEVOLUCION_ESPERADA, FECHA_DEVOLUSION_REAL) VALUES
			("987-2", 2, DATE_SUB(@hoy, INTERVAL 20 DAY), DATE_SUB(@hoy, INTERVAL 5 DAY), @hoy);
            
-- ENTREGA EN TIEMPO Y FORMA
INSERT PRESTAMOS(ISBN, ID_USUARIO, FECHA_PRESTAMO, FECHA_DEVOLUCION_ESPERADA, FECHA_DEVOLUSION_REAL) VALUES
			("987-3", 3, "2025-09-20", "2025-10-05", "2025-10-05");            

select * FROM PRESTAMOS;

SELECT * FROM libros_E 
WHERE AÑO_PUBLICADO > 2000 AND GENERO = "CIENCIA";

SELECT * FROM libros_E
WHERE AUTOR = "ANTONI" AND AÑO_PUBLICADO > 1980;

SELECT * FROM PRESTAMOS 
WHERE FECHA_DEVOLUSION_REAL IS NULL;


SELECT * FROM LIBROS_E
WHERE AÑO_PUBLICADO between 1980 AND 2000
AND NOT GENERO = "TERROR"






