CREATE TABLE CELULARES(
	ID_CELULAR INT,
    MARCA VARCHAR (25),
    MODELO VARCHAR(25),
    COLOR VARCHAR(25),
    PRECIO INT,
    constraint CELULAR_PK primary key (ID_CELULAR)
);

INSERT INTO CELULARES VALUES (1, "SAMSUNG", "GALAXY", "NEGRO", 12000),
								(2, "XIAOMI", "X21", "AZUL", 8000),
                                (3, "HUAWEI", "P30", "BLANCO", 5500),
                                (4, "MOTOROLA", "M123", "VERDE", 2080),
                                (5, "VIVO", "V123", "NARANGA", 11200),
                                (6, "SAMSUNG", "S21", "NEGRO MATE", 18900);
                                
SELECT * FROM CELULARES;

-- COUNT()
SELECT COUNT(*) AS TOTAL FROM CELULARES;

SELECT MARCA, COUNT(*) AS CANTIDAD_POR_MARCA
FROM CELULARES
GROUP BY MARCA;

-- SUM
SELECT CONCAT("$", FORMAT(SUM(PRECIO),2)) AS TOTAL_DE_PRECIOS FROM CELULARES;

-- AVG
select AVG(PRECIO) AS PRECIO_PROMEDIO FROM CELULARES;
SELECT FORMAT(AVG(PRECIO),2) AS PRECIO_PROMEDIO FROM CELULARES;
SELECT ROUND(AVG(PRECIO),2) AS PRECIO_PROMEDIO FROM CELULARES;



-- MIN ME TRAE SOLO EL PRECIO
SELECT MIN(PRECIO) AS PRECIO_MINIMO FROM CELULARES;

-- MIN ME TRAE TODA LA INFOMACION DE EL PRECIO BAJO
SELECT * FROM CELULARES
WHERE PRECIO = (SELECT MIN(PRECIO) FROM CELULARES);

SELECT * FROM CELULARES
WHERE PRECIO = (SELECT MAX(PRECIO) FROM CELULARES);

SELECT MARCA,
	COUNT(*) AS TOTAL_CELULARES,
    SUM(PRECIO) AS TOTAL_PRECIO,
    AVG(PRECIO) AS PRECIO_PORMEDIO,
    MIN(PRECIO) AS PRECIO_MINIMI,
    MAX(PRECIO) AS PRECIO_MAXIMO
FROM CELULARES
GROUP BY MARCA;
    
    

