SELECT * FROM EMPLEADO;

-- CONCAT()
SELECT CONCAT(NOMBRE, "TRABAJA EN", DEPARTAMENTO) AS DETALLE FROM EMPLEADO;

-- UPPER()
SELECT UPPER(NOMBRE) AS NOMBRE_MINUSCULA FROM EMPLEADO;

-- LOWER()
SELECT LOWER(NOMBRE) AS NOMBRE_MINUSCULA FROM EMPLEADO;

-- SUBSTRING
SELECT SUBSTRING(NOMBRE, 1, 4) AS LONGITUD FROM EMPLEADO;

-- LENGTH()
SELECT NOMBRE, LENGTH(NOMBRE) AS LONGITUD FROM EMPLEADO;
SELECT LENGTH("  HOLA  ") AS LONGITUD;

-- TRIM()
SELECT TRIM("  HOLA  ") AS TEXTO_ORIGINAL, LENGTH(TRIM("   HOLA   "))AS CARACTERES;
SELECT TRIM("0" FROM "000000123000") AS NUMERO_LIMPIO;

-- LEFT
SELECT NOMBRE, LEFT(NOMBRE, 4) AS NOMBRE_CORTO FROM EMPLEADO;

-- RIGHT
SELECT NOMBRE, RIGHT(NOMBRE, 4) AS APELLIDO FROM EMPLEADO;

-- LTRIM
SELECT LTRIM ("  HOLA  ") AS RESULTADOS;

-- RTRIM
SELECT RTRIM ("  HOLA  ") AS RESULTADOS;

ALTER TABLE EMPLEADO ADD (CORREO VARCHAR(50)DEFAULt "nombre@correo.com");

SELECT NOMBRE, CORREO, REPLACE(CORREO, "@correo.com", "@gmail.com") as NUEVO_CORREO FROM EMPLEADO;

