-- NOW() FECHA Y HORA ACTUAL
SELECT NOW() AS FECHA_HORA_ACTUAL;

-- CURDATE
SELECT CURDATE() AS FECHA;

-- CURTIME
SELECT CURTIME() AS HORA;

-- YEAR(), MONTH, DAY
SELECT YEAR(NOW()) AS ANIO, MONTH(NOW()) AS MES, DAY(NOW()) AS DIA;

-- HOUR(), MINUTE(), SECOD()
SELECT HOUR(NOW()) AS HORA, MINUTE(NOW()) AS MINUTO, SECOND(NOW()) AS SEGUNDO;

-- CURRENT_DATE()
SELECT CURRENT_DATE() AS FECHA_ACTUAL;

-- CURRENT_TIME
SELECT CURRENT_TIME() AS HORA_ACTUAL;

-- DATE
SELECT DATE(NOW()) AS SOLO_FECHA;

-- TIME
SELECT TIME(NOW()) AS SOLO_HORA;

-- TIMESTAMPDIFF
SELECT TIMESTAMPDIFF(YEAR, "2002-02-22", NOW()) AS EDAD;

-- FORMATOS DE FECHA
SELECT DATE_FORMAT(NOW(), "%d/%m/%y") as FEHCA_FORMATEADA;

SELECT DATE_FORMAT(NOW(), "%W/%m/%y") as FEHCA_FORMATEADA;

SELECT DATE_FORMAT(NOW(), "%W, %d/%m/%y") as FEHCA_FORMATEADA;

SELECT DATE_FORMAT(NOW(), "%a, %d de %m del %y") as FEHCA_FORMATEADA;

-- CALCULAR LA ANTIGUEDAD DE UN EMPLEADO
SELECT * FROM EMPLEADO;

SELECT NOMBRE, FECHA, TIMESTAMPDIFF(MONTH, FECHA, NOW()) AS ANTIGUEDAD FROM EMPLEADO;


-- CAMBIO DE LENGUAJE DEL GESTOR
SET LC_TIME_NAMES = "es_MX"