CREATE TABLE CARROS(
	ID_CARRO INT PRIMARY KEY,
    MARCA VARCHAR(25),
    COLOR VARCHAR(25),
    CANTIDAD INT,
    PRECIO INT
);

INSERT INTO CARROS VALUES (1, "JETTA", "BLANCO", 2, 120000),
							(2, "SENTRA", "ROJO", 5, 100000), 
                            (3, "JEEP", "CAFE", 4, 150000),
                            (4, "TSURU", "NEGRO", 10, 85000), 
                            (5, "AUDI", "BLANCO", 1, 280000),
                            (6, "CAMIONETA", "AZUL", 6, 90000);
                            
SELECT * FROM CARROS;

SELECT MARCA, COLOR, CANTIDAD, CONCAT("$", FORMAT(PRECIO, 2), "PESOS MX") AS PRECIO,
CONCAT("$", FORMAT(PRECIO * CANTIDAD, 2), "PESOS MX") AS TOTAL_VENTA,
(
	CASE 
		WHEN (CANTIDAD * PRECIO) > 400000 THEN "LA VENTA ES MUY ALTA"
        WHEN (CANTIDAD * PRECIO) BETWEEN 250000 AND 400000 THEN "ES BUENA VENTA"
        ELSE "ES UNA VENTA NORMAL"
	END
) AS TIPO_DE_VENTA
FROM CARROS;