CREATE TABLE PERSONA1(
	ID_PERSONA INT,
    NOMBRE VARCHAR(25),
    DIR_ID INT
);
DROP TABLE PERSONA1;
CREATE TABLE DIRECCION(
	ID_DIR INT,
    DIRECCION VARCHAR(50)
    
);

INSERT INTO PERSONA1 VALUES
		(1, "JUAN", 100),
        (2, "RODRIGO", 101),
        (3, "SOFIA", 102),
        (4, "DIEGO", 103),
        (5, "LUIS", 104);
        
INSERT INTO DIRECCION VALUES
		(100, "AV. PRINCI´PAL 123" ),
        (101, "CALLE CENTRAL 123"),
        (103, "FRACC. LIBERTAD 258"),
        (105, "CALLE EL ROBLE 123"),
        (106, "AV. NORTE 369");
        
 -- MUESTRA LOS REGISTROS DONDE EXISTEN ALMENOS UNA COINCIDENCIA       
SELECT P.NOMBRE, P.DIR_ID, D.ID_DIR, D.DIRECCION
FROM PERSONA1 P
INNER JOIN DIRECCION D
ON P.DIR_ID = D.ID_DIR;
        
 -- MUESTRA TODOS LOS REGISTROS DE LA TABLA A Y LAS UNICA COINCIDENCIAS DE LA TABLA B
 SELECT PERSONA1.NOMBRE, PERSONA1.DIR_ID, DIRECCION.ID_DIR, DIRECCION.DIRECCION
 FROM PERSONA1
 LEFT JOIN DIRECCION
 ON PERSONA1.DIR_ID = DIRECCION.ID_DIR;
 
-- MUESTRA TODOS LOS REGISTROS DE L TBLA B Y NICAMENTE LAS COINCIDDENCIAS CON LA TABLA A 
SELECT P.*, D.*
 FROM PERSONA1 P
 RIGHT JOIN DIRECCION D
 ON P.DIR_ID = D.ID_DIR;
 
 -- FULL JOIN
 SELECT *
 FROM PERSONA1
 LEFT JOIN DIRECCION ON PERSONA1.DIR_ID = DIRECCION.ID_DIR
 UNION
 SELECT *
 FROM PERSONA1
 RIGHT JOIN DIRECCION ON PERSONA1.DIR_ID = DIRECCION.ID_DIR;
 
 --
 
 
 
        