CREATE TABLE PERSONA_JOIN(
	ID_PERSONA INT ,
    NOMBRE VARCHAR(25),
    EDAD INT,
    OCUPACION VARCHAR(25),
    DEPORTE_ID INT,
    CONSTRAINT PERSONA_JOINS_PK PRIMARY KEY (ID_PERSONA),
    CONSTRAINT PERSONA_JOINS_FK FOREIGN KEY (DEPORTE_ID) REFERENCES DEPORTES(ID_DEPORTE)
);

CREATE TABLE DEPORTES(
	ID_DEPORTE INT,
    DEPORTE VARCHAR(25),
    CONSTRAINT DEPORTES_PK PRIMARY KEY (ID_DEPORTE)
);

INSERT INTO DEPORTES VALUES
				(101, "FUTBOL"),
                (102, "BASQUET"),
                (103, "VALEYBOL"),
                (104, "GIMNACIA"),
                (105, "BOX");
                
SELECT * FROM DEPORTES;

INSERT INTO PERSONA_JOIN VALUES
		(1, "CESAR RUIZ", 25 , "VENDEDOR", 101),
		(2, "LAURA SANCHEZ", 18 , "CAJERO", 104),
		(3, "RAUL PEREZ", 22 , "CHOFER", NULL),
		(4, "MANUEL MEDINA", 24 , "INFORMATICO", 102),
		(5, "LUPE PERALTA", 20 , "ESTUDIANTE", NULL);

-- INNER JOIN
SELECT *
FROM PERSONA_JOIN P
JOIN DEPORTES D
ON P.DEPORTE_ID = D.ID_DEPORTE; 

-- LEFT JOIN
SELECT P.NOMBRE, P.EDAD, P.OCUPACION, D.DEPORTE
FROM PERSONA_JOIN P
LEFT JOIN DEPORTES D
ON P.DEPORTE_ID = D.ID_DEPORTE;


-- RIGHT JOIN
SELECT * 
FROM PERSONA_JOIN P
RIGHT JOIN DEPORTES D
ON P.DEPORTE_ID = D.ID_DEPORTE;

-- FULL JOIN
SELECT *
FROM PERSONA_JOIN P
LEFT JOIN DEPORTES D
ON P.DEPORTE_ID = D.ID_DEPORTE
UNION
SELECT *
FROM PERSONA_JOIN P
RIGHT JOIN DEPORTES D
ON P.DEPORTE_ID = D.ID_DEPORTE;



                