CREATE TABLE CLIENTE_JOIN (
	ID_CLIENTE INT,
    NOMBRE VARCHAR(50),
    CONSTRAINT CLIENTE_PK PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE PEDIDOS(
	ID_PEDIDO INT,
    CLIENTE_ID INT,
    FECHA_PEDIDO DATE,
    CONSTRAINT PEDIDO_PK PRIMARY KEY (ID_PEDIDO),
    CONSTRAINT PEDIDO_FK FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE_JOIN(ID_CLIENTE)
);

CREATE TABLE DATOS(
	ID_DATO INT,
    PEDIDO_ID INT,
    DETALLES_PEDIDO VARCHAR(50),
    CONSTRAINT DATOS_PF PRIMARY KEY (ID_DATO),
    CONSTRAINT DATOS_FK FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDOS(ID_PEDIDO)
);


INSERT INTO CLIENTE_JOIN VALUES
						(1, "JUAN PEREZ"),
                        (2, "CARLOS LOPEZ"),
                        (3, "PEDRO MEDINA"),
                        (4, "MARIA SANCHEZ"),
                        (5, "ANA SALAZAR");
                        
INSERT INTO PEDIDOS VALUES
						(10, 1, "2025-10-15"),
                        (20, 2, "2025-09-15"),
                        (40, NULL, "2025-11-15"),
                        (30, 4, "2025-10-20"),
                        (50, 5, "2025-10-29");
					
INSERT INTO DATOS VALUES
						(101, 10, "PEDIDO DE ROPA"),
                        (102, 20, "PEDIDO DE ZAPATOS"),
                        (103, 30, "PEDIDO DE REFACCIONES"),
                        (104, 40, "PEDIDO DE TACOS"),
                        (105, NULL, "PEDIDO DE MERCADO LIBRE");
                        
-- INNER JOIN
SELECT *
FROM CLIENTE_JOIN C
JOIN PEDIDOS P
ON C.ID_CLIENTE = P.CLIENTE_ID
JOIN DATOS D
ON P.ID_PEDIDO = D.PEDIDO_ID;

-- LEFT JOIN
SELECT C.*, PE.*, D.*
FROM CLIENTE_JOIN C 
LEFT JOIN PEDIDOS PE 
ON C.ID_CLIENTE = PE.CLIENTE_ID
LEFT JOIN DATOS D
ON PE.ID_PEDIDO = D.PEDIDO_ID;


-- RIGHT JOIN
SELECT C.NOMBRE, PE.FECHA_PEDIDO, D.DETALLE_PEDIDO
FROM CLIENTE_JOIN  C
RIGHT JOIN PEDIDOS PE
ON C.ID_CLIENTE = PE.CLIENTE_ID
RIGHT JOIN DATOS D
ON PE.ID_PEDIDO = D.PEDIDO_ID;

-- FULL JOIN
SELECT * 
FROM CLIENTE_JOIN C
LEFT JOIN PEDIDOS PE ON C.ID_CLIENTE = PE.CLIENTE_ID
LEFT JOIN DATOS D ON PE.ID_PEDIDO = D.PEDIDO_ID
UNION
SELECT *
FROM CLIENTE_JOIN C
RIGHT JOIN PEDIDOS PE ON C.ID_CLIENTE = PE.CLIENTE_ID
RIGHT JOIN DATOS D ON PE.ID_PEDIDO = D.PEDIDO_ID;

