USE ENUCOM;

CREATE TABLE MEDICOS(
	ID_MEDICO INT,
    NOMBRE VARCHAR (50),
    ESPECIALIDAD VARCHAR(30),
    SUELDO DECIMAL (10,2),
    DIRECCION VARCHAR(50),
    ID_HOSPITAL INT,
    PRIMARY KEY (ID_MEDICO),
    FOREIGN KEY (ID_HOSPITAL) REFERENCES HOSPITAL(ID_HOSPITAL)
);

CREATE TABLE HOSPITAL (
	ID_HOSPITAL INT,
    NOMBRE VARCHAR(50),
    PRIMARY KEY (ID_HOSPITAL)
);

INSERT INTO HOSPITAL VALUES 
						(1, "HOSPITAL DEL NIÑO POBLANO"),
					    (2, "HOSPITAL DE LA MUJER"),
                        (3, "HOSPITAL SAN ALEJANDRO"),
                        (4, "HOSPITAL DE LOS ANGELES"),
                        (5, "HOSPITAL ESPAÑOL");
                        
                        
INSERT INTO MEDICOS VALUES 
						(1, "DR. JUAN PEREZ", "NEUROLOGO", 60000, "AV. PRINCIPAL 123", 4),
                        (2, "DR. LUIS SANCHEZ", "PEDIATRA", 50000, "AV. CENTRAL 123", 1),
                        (3, "DR. MARIO LARA", "GINECOLOGO", 65000, "AV. FRESNO 123", 2),
                        (4, "DR. DIEGO RUIZ", "NEUROLOGO", 45000, "AV. PRINCIPAL 123", 5),
                        (5, "DR. ANA AGUILAR", "NEUROLOGO", 60000, "AV. CEDRO 123", 3),
                        (6, "DR. GERARDO SOLAR", "NEUROLOGO", 59000, "AV. ENSINO 123", NULL);
                        
CREATE OR REPLACE VIEW V_INF_MEDICOS
AS
SELECT M.ID_MEDICO AS ID, M.NOMBRE AS MEDICO,
M.ESPECIALIDAD, H.NOMBRE AS HOSPITAL
FROM MEDICOS M
JOIN HOSPITAL H
ON M.ID_HOSPITAL = H.ID_HOSPITAL;

SELECT * FROM V_INF_MEDICOS;


CREATE OR REPLACE VIEW V_INFO_MEDICO_HOSPITAL
AS 
SELECT M.ID_MEDICO AS ID, M.NOMBRE AS MEDICO,
M.ESPECIALIDAD,
CASE 
	WHEN M.ID_HOSPITAL IS NULL THEN "SIN HOSPITAL ASIGNADO"
    ELSE H.NOMBRE
END AS HOSPITAL
FROM MEDICOS M
LEFT JOIN HOSPITAL H
ON M.ID_HOSPITAL = H.ID_HOSPITAL;

SELECT * FROM V_INFO_MEDICO_HOSPITAL;



CREATE OR REPLACE VIEW V_MEDICOS_ESP
AS 
SELECT ID_MEDICO, NOMBRE, ESPECIALIDAD
FROM MEDICOS
WHERE ESPECIALIDAD = "NEUROLOGO";

SELECT * FROM V_MEDICOS_ESP













