CREATE TABLE SECCIONES (
	CODIGO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(20),
    SUELDO DECIMAL(10,2)
);

CREATE TABLE EMPLEADO_VISTA(
	ID_EMPLEADO INT AUTO_INCREMENT PRIMARY KEY,
    CLAVE CHAR(10),
    GENERO CHAR (1),
    APELLIDO VARCHAR(20),
    NOMBRE VARCHAR (50),
    DOMICILIO VARCHAR(50),
    SECCION INT NOT NULL,
    ESTADO_CIVIL CHAR(1),
    FECHAR_INGRESO DATE
);

INSERT INTO SECCIONES (NOMBRE, SUELDO)VALUES
									("ADMINISTRACION", 26000),
                                    ("REDES", 35000),
                                    ("LEGAL", 32000),
                                    ("RH", 20000);
						
INSERT INTO EMPLEADO_VISTA (CLAVE, GENERO, APELLIDO, NOMBRE, DOMICILIO, SECCION, ESTADO_CIVIL, FECHAR_INGRESO) VALUES
("AA1", "M", "HERNADEZ", "JAIME", "CALLE SEDRO 123", 1, "C", "2000-03-15"),
("AA2", "F", "LOPEZ", "MARIA", "CALLE ENCINO 123", 2, "S", "2015-03-20"),
("AA3", "M", "SOLAR", "RAUL", "AV. PRINCIPAL 123", 3, "C", "2010-09-16"),
("AA4", "F", "SANCHEZ", "ANA", "AV. CENTRAL 123", 4, "C", "2023-05-22"),
("AA5", "M", "PEREZ", "JUAN", "CALLE FRENO 123", 2, "C", "2009-02-08");


SELECT * FROM EMPLEADO_VISTA;


CREATE OR REPLACE VIEW V_EMPLEADOS
AS
SELECT CONCAT(E.APELLIDO, " ",E.NOMBRE) AS NOMBRE,
E.GENERO, E.FECHAR_INGRESO, S.NOMBRE AS SECCION
FROM EMPLEADO_VISTA E
JOIN SECCIONES S
ON S.CODIGO = E.SECCION;

SELECT * FROM V_EMPLEADOS;



CREATE OR REPLACE VIEW INFO_EMPLEADO
AS
SELECT CONCAT(E.NOMBRE, " ", E.APELLIDO) AS NOMBRE_COMPLETO,
CASE E.GENERO	
	WHEN "M" THEN "MASCULINO"
    WHEN "F" THEN "FEMENINO"
    ELSE "OTRO"
END AS GENERO, S.NOMBRE AS SECCION,
CASE E.ESTADO_CIVIL
	WHEN "C" THEN "CASADO"
    WHEN "S" THEN "SOLTERO"
    ELSE "UNIO LIBRE"
END AS ESTADO_CIVIL,
CONCAT(TIMESTAMPDIFF(YEAR, E.FECHAR_INGRESO, CURDATE()), "AÑOS") AS ANIOS_LABORANDO
FROM EMPLEADO_VISTA E
JOIN SECCIONES S
ON E.SECCION = S.CODIGO;

SELECT * FROM INFO_EMPLEADO;
















