SELECT * FROM TRABAJADORES;

DESCRIBE TRABAJADORES;
use enucom;
CREATE TABLE TRABAJADORES(
	ID_TRABAJADOR INT PRIMARY KEY,
    NOMBRE VARCHAR(20),
    TIPO VARCHAR(50),
    SALARIO DECIMAL(10,2)
);

INSERT INTO TRABAJADORES (ID_TRABAJADOR, NOMBRE, TIPO, SALARIO) VALUES (1, 'Laura Pérez', 'Administrativo', 15000.00);
INSERT INTO TRABAJADORES (ID_TRABAJADOR, NOMBRE, TIPO, SALARIO) VALUES (2, 'José García', 'Operario', 17500.00);
INSERT INTO TRABAJADORES (ID_TRABAJADOR, NOMBRE, TIPO, SALARIO) VALUES (3, 'Ana Torres', 'Analista', 20000.00);
INSERT INTO TRABAJADORES (ID_TRABAJADOR, NOMBRE, TIPO, SALARIO) VALUES (4, 'Mario López', 'Jefe de área', 25000.00);
INSERT INTO TRABAJADORES (ID_TRABAJADOR, NOMBRE, TIPO, SALARIO) VALUES (5, 'Carmen Ruiz', 'Auxiliar', 13000.50);
INSERT INTO TRABAJADORES (ID_TRABAJADOR, NOMBRE, TIPO, SALARIO) VALUES (6, 'Pedro Ramírez', 'Operario', 18000.75);
INSERT INTO TRABAJADORES (ID_TRABAJADOR, NOMBRE, TIPO, SALARIO) VALUES (7, 'Lucía Herrera', 'Analista', 21000.00);
INSERT INTO TRABAJADORES (ID_TRABAJADOR, NOMBRE, TIPO, SALARIO) VALUES (8, 'Sofía Jiménez', 'Administrativo', 15500.00);
INSERT INTO TRABAJADORES (ID_TRABAJADOR, NOMBRE, TIPO, SALARIO) VALUES (9, 'Javier Moreno', 'Jefe de área', 27000.00);
INSERT INTO TRABAJADORES (ID_TRABAJADOR, NOMBRE, TIPO, SALARIO) VALUES (10, 'Paula Díaz', 'Auxiliar', 13500.25);



CREATE TABLE RESPALDO_TRABAJADORES(
	ID_TRABAJADOR INT PRIMARY KEY,
    NOMBRE VARCHAR(20),
    TIPO VARCHAR(50),
    SALARIO DECIMAL(10,2)
);

DELIMITER //

CREATE PROCEDURE PR_RESPALDO_TRABAJADORES()
BEGIN
	DELETE FROM RESPALDO_TRABAJADORES;
	INSERT INTO RESPALDO_TRABAJADORES (ID_TRABAJADOR, NOMBRE, TIPO, SALARIO)
    SELECT ID_TRABAJADOR, NOMBRE, TIPO, SALARIO FROM TRABAJADORES;
    
END //

DELIMITER ;

DROP PROCEDURE PR_RESPALDO_TRABAJADORES;
SELECT * FROM TRABAJADORES;
SELECT * FROM RESPALDO_TRABAJADORES;

SET SQL_SAFE_UPDATES = 0;

DELETE FROM RESPALDO_TRABAJADORES;
-- EJECUTAMOS EL PROCEDIMIENTOS
CALL PR_RESPALDO_TRABAJADORES();
INSERT INTO TRABAJADORES (ID_TRABAJADOR, NOMBRE, TIPO, SALARIO) VALUES (12, 'Juan Díaz', 'Almacen', 11500.25);
