SELECT * FROM PERROS;

CREATE TABLE CONTROL(
	USUARIO VARCHAR(25),
    FECHA DATETIME,
    MOVIMIENTO VARCHAR(25)
);

DELIMITER //

CREATE TRIGGER TR_INGRESO_CONTROL
BEFORE INSERT
ON PERROS
FOR EACH ROW
BEGIN
	INSERT INTO CONTROL VALUES(USER(), NOW(), "INSERT");
    
END //

DELIMITER ;

SELECT * FROM PERROS;
SELECT * FROM CONTROL;

INSERT INTO PERROS VALUES (7, "FIRULAS", "NEGRO", 1, 20);


-- ---------------------------------------------------
DELIMITER //

CREATE TRIGGER TR_ACTUALIZAR_CONTROL
BEFORE UPDATE
ON PERROS
FOR EACH ROW
BEGIN
	INSERT INTO CONTROL VALUES(USER(), NOW(), "UPDATE");
    
END //

DELIMITER ;

SELECT * FROM PERROS;
SELECT * FROM CONTROL;

UPDATE PERROS SET COLOR = "MANCHADO"
WHERE ID_PERRO = 10;

UPDATE PERROS SET RAZA = 6 WHERE ID_PERRO IN (2,4,6)

-- -------------------------------------------------------------

DELIMITER //

CREATE TRIGGER TR_ELIMINAR_CONTROLS
BEFORE DELETE
ON PERROS
FOR EACH ROW
BEGIN
	INSERT INTO CONTROL VALUES(USER(), NOW(), "DELETE");
    
END //

DELIMITER ;

SELECT * FROM PERROS;
SELECT * FROM CONTROL;

DELETE FROM PERROS WHERE ID_PERRO = 6;
DELETE FROM PERROS WHERE ID_PERRO IN (7, 8, 9);



