CREATE TABLE PROFESIONISTA(
	ID_PRO INT,
    NOMBRE VARCHAR(50),
    EDAD INT,
    TIPO VARCHAR(20),
    SUELDO DECIMAL(10,2)
);

CREATE TABLE BITACORA(
	-- PK
    ID_BITACORA INT,
    -- VALORES NUEVOS
    ID_PRO INT,
    NOMBRE VARCHAR(50),
    EDAD INT,
    TIPO VARCHAR(50),
    SUELDO DECIMAL(10,2),
    -- VALORES ORIGINALES
    NOMBRE_OLD VARCHAR(50),
    EDAD_OLD INT,
    TIPO_OLD VARCHAR(50),
    SUELDO_OLD DECIMAL(10,2),
    -- CAMPOS CONTROL
    USUARIO VARCHAR(50),
    FECHA_NACIMIENTO DATETIME,
    MOVIMIENTO VARCHAR(20),
    PRIMARY KEY (ID_BITACORA)
);


DELIMITER //

CREATE TRIGGER TR_I_PRO
BEFORE INSERT
ON PROFESIONISTA
FOR EACH ROW
BEGIN
	-- VARIABLES LOCALES
    DECLARE LV_ID_BIT INT;
    DECLARE LV_USUARIO VARCHAR(20);
    DECLARE LV_FECHA DATETIME;
    
    -- OBTENEMOS EL USUARIOY LA FECHA
    SET LV_USUARIO = USER();
    SET LV_FECHA = NOW();
    
    -- OBTENEMOS UN ID VALIDO PARA LA BITACORA
    -- SI NO HAY NINGUNA VITACORA LE SUMAMOS 1
    SELECT IFNULL(MAX(ID_BITACORA), 0) + 1 INTO LV_ID_BIT FROM BITACORA;    
    -- LV_ID_BIT = 1
    
    -- REGISTROS HISTORICOS
    INSERT INTO BITACORA VALUES 
    (LV_ID_BIT, NEW.ID_PRO, NEW.NOMBRE, NEW.EDAD,
    NEW.TIPO, NEW.SUELDO, NULL, 0, NULL, 0, LV_USUARIO, LV_FECHA, "INSERT");
    
END //

DELIMITER ;

SELECT *FROM PROFESIONISTA;
SELECT *FROM BITACORA;

INSERT INTO PROFESIONISTA VALUES (1, "JUAN", 35, "MEDICO", 25000);

INSERT INTO PROFESIONISTA VALUES 
(2, "PABLO", 25, "PROGRAMADOR", 35000),
(3, "RAUL", 40, "ABOGADO", 29000);

-- -----------------------------------------------------------------
USE ENUCOM;
DELIMITER //

CREATE TRIGGER TR_U_PRO
BEFORE UPDATE
ON PROFESIONISTA
FOR EACH ROW
BEGIN
	-- VARIABLES LOCALES
    DECLARE LV_ID_BIT INT;
    DECLARE LV_USUARIO VARCHAR(20);
    DECLARE LV_FECHA DATETIME;
    
    -- OBTENEMOS EL USUARIOY LA FECHA
    SET LV_USUARIO = USER();
    SET LV_FECHA = NOW();
    
    -- OBTENEMOS UN ID VALIDO PARA LA BITACORA
    -- SI NO HAY NINGUNA VITACORA LE SUMAMOS 1
    SELECT IFNULL(MAX(ID_BITACORA), 0) + 1 INTO LV_ID_BIT FROM BITACORA;    
    -- LV_ID_BIT = 1
    
    -- REGISTROS HISTORICOS
    INSERT INTO BITACORA VALUES (LV_ID_BIT, NEW.ID_PRO, NEW.NOMBRE, NEW.EDAD,NEW.TIPO, NEW.SUELDO, 
    OLD.NOMBRE, OLD.EDAD, OLD.TIPO, OLD.SUELDO, LV_USUARIO, LV_FECHA, "UPDATE");
    
END //

DELIMITER ;

SELECT *FROM PROFESIONISTA;
SELECT *FROM BITACORA;

UPDATE PROFESIONISTA SET EDAD = 37, TIPO = "DOCTOR", SUELDO = 2700 WHERE ID_PRO = 1;
UPDATE PROFESIONISTA SET EDAD = 20, TIPO = "ESTUDIANTE", SUELDO = 10000 WHERE ID_PRO IN (2,3);

SET SQL_SAFE_UPDATES = 0;

DROP TRIGGER TR_D_PRO;
DELIMITER //

CREATE TRIGGER TR_D_PRO
BEFORE DELETE
ON PROFESIONISTA
FOR EACH ROW
BEGIN
	-- VARIABLES LOCALES
    DECLARE LV_ID_BIT INT;
    
    -- OBTENEMOS UN ID VALIDO PARA LA BITACORA
    -- SI NO HAY NINGUNA VITACORA LE SUMAMOS 1
    SELECT IFNULL(MAX(ID_BITACORA), 0) + 1 INTO LV_ID_BIT FROM BITACORA;    
    -- LV_ID_BIT = 1
    
    -- REGISTROS HISTORICOS
    INSERT INTO BITACORA VALUES (LV_ID_BIT, OLD.ID_PRO, NULL, 0, NULL, 0,
    OLD.NOMBRE, OLD.EDAD, OLD.TIPO, OLD.SUELDO, USER(), NOW(), "DELETE");
    
END //

DELIMITER ;

SELECT *FROM PROFESIONISTA;
SELECT *FROM BITACORA;

DELETE FROM PROFESIONISTA WHERE ID_PRO = 1;

-- ----------------------------------------------------------------------------

CREATE TABLE CONTROL_SUELDO(
	ID_CONTROL INT AUTO_INCREMENT PRIMARY KEY,
    ID_PRO INT,
    SUELDO_NEW DECIMAL(10,2),
    SUELDO_OLD DECIMAL(10,2),
    MENSAJE VARCHAR(150),
    FECHA DATE DEFAULT (CURDATE())
);

SELECT * FROM CONTROL_SUELDO;
DROP TRIGGER TR_CONTROL_SUELDO;
DELIMITER //

CREATE TRIGGER TR_CONTROL_SUELDO
AFTER UPDATE
ON PROFESIONISTA
FOR EACH ROW
BEGIN
	IF NEW.SUELDO > OLD.SUELDO THEN 
		INSERT INTO CONTROL_SUELDO (ID_PRO, SUELDO_NEW, SUELDO_OLD, MENSAJE) VALUES
        (NEW.ID_PRO, NEW.SUELDO, OLD.SUELDO, "FELICIDADES!!, RECIBISTE UN AUMENTO");
        
	ELSEIF NEW.SUELDO < OLD.SUELDO  THEN
		INSERT INTO CONTROL_SUELDO (ID_PRO, SUELDO_NEW, SUELDO_OLD, MENSAJE) VALUES
		(NEW.ID_PRO, NEW.SUELDO, OLD.SUELDO, "TUVISTE UN DESCUENTO EN TU SUELDO");
        
	ELSE 
		INSERT INTO CONTROL_SUELDO (ID_PRO, SUELDO_NEW, SUELDO_OLD, MENSAJE) VALUES
		(NEW.ID_PRO, NEW.SUELDO, OLD.SUELDO, "SUELDO ACTUAL SIN CAMBIOS");
        
	END IF;
    
END //

DELIMITER ;

SELECT *FROM PROFESIONISTA;
SELECT *FROM BITACORA;
SELECT * FROM CONTROL_SUELDO;

UPDATE PROFESIONISTA SET SUELDO = 26000 WHERE ID_PRO = 1;
UPDATE PROFESIONISTA SET SUELDO = 19000 WHERE ID_PRO = 2;



