DELIMITER //

CREATE PROCEDURE PR_I_TRABAJADORES(
	IN PI_ID_TRABAJADOR INT,
    IN PI_NOMBRE VARCHAR(50),
    IN PI_TIPO VARCHAR(25),
    IN PI_SALARIO INT,
    OUT PO_ESTATUS VARCHAR(200)
)
BEGIN
	INSERT INTO TRABAJADORES VALUES (PI_ID_TRABAJADOR, PI_NOMBRE, PI_TIPO, PI_SALARIO);
    IF ROW_COUNT() > 0 THEN
		SET PO_ESTATUS = CONCAT("EL TRABAJADOR ", PI_NOMBRE, "SE INSETO CORRECTAMENTE");
	ELSE 
		SET PO_ESTATUS = "ERROR!, NO SE PUDO INSERTA EL TRABAJDOR";
	END IF;
END //

DELIMITER ;

SELECT * FROM TRABAJADORES;

-- EJECUTAMOS EL PROCEDIMIENTOS
CALL PR_I_TRABAJADORES(13, "MARIO PEREZ", "PILOTO", 6500, @MENSAJE);

SELECT @MENSAJE;