SELECT * FROM POSTRES;
DESCRIBE POSTRES;
DROP PROCEDURE PR_I_POSTRES;

DELIMITER //

CREATE PROCEDURE PR_I_POSTRES(
	IN PI_ID INT,
    IN PI_TIPO VARCHAR(25),
    IN PI_PRECIO INT,
    IN PI_EVENTO VARCHAR(200)
)

BEGIN
	DECLARE MENSAJE VARCHAR(100);
    
    IF PI_EVENTO = "INSERT" THEN
		INSERT INTO POSTRES (ID_POSTRE, TIPO, PRECIO) VALUES (PI_ID, PI_TIPO, PI_PRECIO);
        
    ELSEIF PI_EVENTO = "UPDATE" THEN
		UPDATE POSTRES
        SET TIPO = PI_TIPO,
			PRECIO = PI_PRECIO
		WHERE ID_POSTRE = PI_ID;
	
    ELSEIF PI_EVENTO = "DELETE" THEN 
		DELETE FROM POSTRES WHERE ID_POSTRE = PI_ID;
        
	END IF;
    
    IF ROW_COUNT() > 0 THEN
		SET MENSAJE = "PROCEDIMIETO EJECUTADO CORRECTAMENTE";
	ELSE 
		SET MENSAJE = "ERROR! NO SE PUDO EJECUTAR EL PROCEDIMIENTO";
	END IF;
    
    SELECT MENSAJE AS MENSAJE_SALIDA;
END //

DELIMITER ;

-- INSERT
CALL PR_I_POSTRES(7, "PASTEL 3 LECHES", 160, "INSERT");

-- UPDATE
CALL PR_I_POSTRES(7, "TRUFAS", 250, "UPDATE");

-- DELETE 
CALL PR_I_POSTRES(7, NULL, NULL, "DELETE")









