-- Funcion que calcula una edad a partir de una fecha de nacimiento
DELIMITER //

CREATE FUNCTION FN_CALCULAR_EDAD (FECHA_NACIMIENTO DATE)
RETURNS INT
NOT DETERMINISTIC -- INCIDA QUE LA FUNCION DEVUELVE UN VALOR DIFERENTE  PERO LOS PARAMETROS NO CAMBIAN
NO SQL -- INDICA QUE NO ES CONSULTA SQL
BEGIN 
	DECLARE EDAD INT;
    SET EDAD = TIMESTAMPDIFF(YEAR, FECHA_NACIMIENTO, CURDATE());
    RETURN EDAD;
END //
DELIMITER ;

-- EJECUTAR LA FUNCION
SELECT FN_CALCULAR_EDAD("2001-03-31") AS MI_EDAD;

-- ----------------------------------------------------------------
-- FUNCON QUE CALCULE EL IVA

DELIMITER //

CREATE FUNCTION FN_CALCULAR_IVA(PRECIO DECIMAL(10,2), PORCENTAJE INT)
RETURNS DECIMAL(10,2)
DETERMINISTIC -- INDICA QUE DEVUELVE SIEMPRE EL MISMO RESULTADO, SIEMPRE Y CUANDO LOS PARAMETROS SEAN LOS MISMOS
BEGIN
	DECLARE IVA DECIMAL(10,2);
    SET IVA = PRECIO * (PORCENTAJE / 100);
    RETURN IVA;
END //

DELIMITER ;

SELECT * FROM PRODUCTOS;
SELECT NOMBRE, PRECIO, FN_CALCULAR_IVA(PRECIO, 16) AS IVA
FROM PRODUCTOS;

-- ---------------------------------------------------------
-- FUNCION QUE LE DA FORMATO A UN NUMERO 
DELIMITER //

CREATE FUNCTION FN_FORMATO_PRECIO(MONTO DECIMAL(10,2))
RETURNS VARCHAR(30)
DETERMINISTIC
BEGIN 
	RETURN CONCAT("$", FORMAT(MONTO, 2));
END //

DELIMITER ;

SELECT NOMBRE, FN_FORMATO_PRECIO(PRECIO) AS PRECIO_CON_FORMATO
FROM PRODUCTOS;

-- ----------------------------------------------------------------------------
-- FUNCION QUE CALCULA EL INDICE DE MASA CORPORAR DE UNA PERSONA

CREATE TABLE PERSONAS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50),
    PESO DECIMAL(5,2),
    ALTURA DECIMAL(3,2)
);

SELECT * FROM PERSONAS;

INSERT INTO PERSONAS (NOMBRE, PESO, ALTURA) VALUES
("JUAN", 70.6, 1.80),
("MARIA", 67.5, 1.65),
("LUIS", 85.5, 1.70),
("SUSANA", 51, 1.60),
("GERARDO", 99.6, 1.66);

DELIMITER //

CREATE FUNCTION FN_CALCULAR_IMC(PESO DECIMAL(5,2), ALTURA DECIMAL(3,2))
RETURNS DECIMAL(5,2)
DETERMINISTIC
BEGIN 
	DECLARE IMC DECIMAL(5,2);
    
    IF ALTURA <=0 THEN 
		RETURN NULL;
	END IF;
    
    SET IMC = PESO / (ALTURA * ALTURA);
    
    RETURN ROUND(IMC, 2);
    
END //

DELIMITER ;

SELECT NOMBRE, PESO, ALTURA, FN_CALCULAR_IMC(PESO, ALTURA) AS IMC FROM PERSONAS;

-- --------------------------------------------------------------------------
DELIMITER //

CREATE FUNCTION FIN_CATEGORIZACION_IMC(IMC DECIMAL(5,2))
RETURNS VARCHAR(100)
DETERMINISTIC
BEGIN 
	RETURN CASE
		WHEN IMC IS NULL THEN "Datos invalidos"
		WHEN IMC < 18.5 THEN "Bajo peso"
		WHEN IMC BETWEEN 18.5 AND 24.5 THEN "Peso Normal"
		WHEN IMC BETWEEN 25 AND 29.9 THEN "Sobre peso"
		WHEN IMC BETWEEN 30 AND 34.9 THEN "Obesidad"
		ELSE "OBESIDAD MORBIDA"
    
	END ;
END //
DELIMITER ;

SELECT NOMBRE, PESO, ALTURA, FN_CALCULAR_IMC(PESO, ALTURA) AS IMC,
FIN_CATEGORIZACION_IMC(FN_CALCULAR_IMC(PESO, ALTURA)) AS CATEGORIA
FROM PERSONAS







