CREATE TABLE SUPER_MERCADO(
	CODIGO INT PRIMARY KEY,
    PRODUCTO VARCHAR(30),
    AREA VARCHAR(20),
    PERECEDERO CHAR(5),
    FECHA_VENCIMIENTO DATE,
    PRECIO DECIMAL(10,2)
);
SELECT * FROM SUPER_MERCADO;

DROP TABLE SUPER_MERCADO;
DROP TABLE BITACORA_SUPER;

CREATE TABLE BITACORA_SUPER(
	-- PK
    ID_BITACORA INT AUTO_INCREMENT,
    -- VALORES NUEVOS
    CODIGO INT,
    PRODUCTO VARCHAR(30),
    AREA VARCHAR(20),
    PERECEDERO CHAR(5),
    FECHA_VENCIMIENTO DATE,
    PRECIO DECIMAL(10,2),
    -- VALORES ORIGINALES
    CODIGO_OLD INT,
    PRODUCTO_OLD VARCHAR(50),
    AREA_OLD VARCHAR(20),
    PERECEDERO_OLD CHAR(5),
    FECHA_VENCIMIENTO_OLD DATE,
    PRECIO_OLD DECIMAL(10,2),
    -- CAMPOS CONTROL
    USUARIO VARCHAR(50),
    FECHA DATETIME,
    MOVIMIENTO VARCHAR(20),
    PRIMARY KEY (ID_BITACORA)
);

DROP TABLE OFERTAS;
CREATE TABLE OFERTAS(
	ID_OFERTA INT PRIMARY KEY AUTO_INCREMENT,
    PRODUCTO VARCHAR(30),
    FECHA_VENCIMIENTO DATE, 
    PRECIO_OLD DECIMAL(10,2),
    PRECIO_NEW DECIMAL(10,2),
    
    USUARIO VARCHAR(50),
    FECHA DATETIME,
    MOVIMIENTO VARCHAR(20),
    MENSAJE VARCHAR(40)
);

-- -------------------------------------------------------------------------------------------
-- Procedimiento para INSERT, UPDATE Y DELETE con TRIGGER
 DROP TRIGGER TRG_INSERT_SUPERMERCADO;
DELIMITER //

CREATE TRIGGER TRG_INSERT_SUPERMERCADO
AFTER INSERT ON SUPER_MERCADO
FOR EACH ROW
BEGIN
	
    DECLARE LV_ID_BIT INT;
    
    INSERT INTO BITACORA_SUPER
    VALUES (
		LV_ID_BIT,
        NEW.CODIGO, NEW.PRODUCTO, NEW.AREA, NEW.PERECEDERO, NEW.FECHA_VENCIMIENTO, NEW.PRECIO,
		NULL, NULL, NULL, NULL, NULL, NULL,
        USER(), NOW(), 'INSERT'
    );
END//

DELIMITER ;

SELECT * FROM BITACORA_SUPER;
SELECT * FROM SUPER_MERCADO;
INSERT INTO SUPER_MERCADO VALUES (1, "YOGURT", "LACTEOS", "NO", "2025-10-15", 30.00);
INSERT INTO SUPER_MERCADO VALUES (2, "JAMON", "CARNES", "NO", "2025-10-20", 40.00);
-- ----------------------------------------------------
DROP TRIGGER TRG_UPDATE_SUPERMERCADO;
DELIMITER //

CREATE TRIGGER TRG_UPDATE_SUPERMERCADO
AFTER UPDATE ON SUPER_MERCADO
FOR EACH ROW  -- CADA QUE AYA ALGUN CAMBIO
BEGIN
    -- Insertar en bitácora sin manejar ID manualmente
    INSERT INTO BITACORA_SUPER(
        CODIGO, PRODUCTO, AREA, PERECEDERO, FECHA_VENCIMIENTO, PRECIO,
        CODIGO_OLD, PRODUCTO_OLD, AREA_OLD, PERECEDERO_OLD, FECHA_VENCIMIENTO_OLD, PRECIO_OLD,
        USUARIO, FECHA, MOVIMIENTO
    )
    VALUES (
        NEW.CODIGO, NEW.PRODUCTO, NEW.AREA, NEW.PERECEDERO, NEW.FECHA_VENCIMIENTO, NEW.PRECIO,
        OLD.CODIGO, OLD.PRODUCTO, OLD.AREA, OLD.PERECEDERO, OLD.FECHA_VENCIMIENTO, OLD.PRECIO,
        USER(), NOW(), 'UPDATE'
    );

    -- Condición 1: registro en OFERTAS si el precio nuevo es menor al original
    IF NEW.PRECIO < OLD.PRECIO THEN -- SI EL PRECIO NUEVO ES MENOR AL VIEJI(ANTERIOR)
        INSERT INTO OFERTAS (
            PRODUCTO, FECHA_VENCIMIENTO, PRECIO_OLD, PRECIO_NEW,
            USUARIO, FECHA, MOVIMIENTO, MENSAJE
        )
        VALUES (
            NEW.PRODUCTO, NEW.FECHA_VENCIMIENTO, OLD.PRECIO, NEW.PRECIO,
            USER(), NOW(), 'DESCUENTO', 'PRODUCTO EN DESCUENTO'  -- MANDAR MENSAJE DEL OFERTON
        );
    END IF; -- POR OTRO LADO SI 

    -- Condición 2: registrar oferta si la fecha de vencimiento es menor o igual a 5 días desde hoy
    IF NEW.FECHA_VENCIMIENTO IS NOT NULL AND DATEDIFF(NEW.FECHA_VENCIMIENTO, CURDATE()) <= 5 THEN
        IF NOT EXISTS ( -- Si el producto no tiene un registro existente en OFERTAS con un movimiento igual a '60% DE DESCUENTO',
            SELECT 1 FROM OFERTAS o WHERE o.PRODUCTO = NEW.PRODUCTO AND o.MOVIMIENTO = '60% DE DESCUENTO'
        ) THEN														-- 
            INSERT INTO OFERTAS (
                PRODUCTO, FECHA_VENCIMIENTO, PRECIO_OLD, PRECIO_NEW,
                USUARIO, FECHA, MOVIMIENTO, MENSAJE
            )
            VALUES (
                NEW.PRODUCTO, NEW.FECHA_VENCIMIENTO, NEW.PRECIO, NEW.PRECIO * 0.4, -- Inserta una oferta con 60% de descuento (nuevo precio = 40% del precio actual).
                USER(), NOW(), '60% DE DESCUENTO', '60% DE DESCUENTO'
            );
        END IF;
    END IF;
END//

DELIMITER ;
SELECT * FROM BITACORA_SUPER;
SELECT * FROM SUPER_MERCADO;
SELECT * FROM OFERTAS;
UPDATE SUPER_MERCADO SET FECHA_VENCIMIENTO = "2025-10-12" WHERE CODIGO = 2;
 -- -------------------------------------------------------------------------------------------

DELIMITER //

CREATE TRIGGER TRG_DELETE_SUPERMERCADO
AFTER DELETE ON SUPER_MERCADO
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA_SUPER(
        CODIGO, PRODUCTO, AREA, PERECEDERO, FECHA_VENCIMIENTO, PRECIO,
        CODIGO_OLD, PRODUCTO_OLD, AREA_OLD, PERECEDERO_OLD, FECHA_VENCIMIENTO_OLD, PRECIO_OLD,
        USUARIO, FECHA, MOVIMIENTO
    )
    VALUES (
        NULL, NULL, NULL, NULL, NULL, NULL,
        OLD.CODIGO, OLD.PRODUCTO, OLD.AREA, OLD.PERECEDERO, OLD.FECHA_VENCIMIENTO, OLD.PRECIO,
        USER(), NOW(), 'DELETE'
    );
END//

DELIMITER ;

SELECT * FROM BITACORA_SUPER;
SELECT * FROM SUPER_MERCADO;
SELECT * FROM OFERTAS;
DELETE FROM SUPER_MERCADO WHERE CODIGO = 2;
 -- --------------------------------------------------------





