USE ENUCOM;	
-- TABLAS NORMALES
CREATE TABLE PROVEEDORES (
	ID_PROVEEDOR INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(20), 
    APELLIDO VARCHAR(20),
    TELEFONO INT
);
DROP TABLE PROVEEDORES;

INSERT INTO PROVEEDORES (NOMBRE, APELLIDO, TELEFONO) VALUES
('Juan', 'Pérez', 555123456),
('María', 'Gómez', 555654321),
('Carlos', 'Ramírez', 555987654),
('Lucia', 'Torres', 555321789),
('Andrés', 'Soto', 555456123);
SELECT * FROM PROVEEDORES;

DROP TABLE BEBIDAS;
CREATE TABLE BEBIDAS(
	ID_BEBIDA INT AUTO_INCREMENT,
    NOMBRE_BEBIDA VARCHAR(20),
    TIPO VARCHAR(20),
    MARCA VARCHAR(20),
    PRECIO DECIMAL(10,2),
    ID_PROVEEDOR INT,
    CONSTRAINT PK_BEBIDA PRIMARY KEY (ID_BEBIDA),
    CONSTRAINT FK_BEBIDA FOREIGN KEY(ID_PROVEEDOR) REFERENCES PROVEEDORES(ID_PROVEEDOR)
);

DROP TABLE BITACORA_BEBIDAS;
-- TABLAS DE BITACORAS
CREATE TABLE BITACORA_BEBIDAS(
	ID_BITACORA INT AUTO_INCREMENT,
    -- VALORES NUEVOS
    NOMBRE_BEBIDA VARCHAR(20),
    TIPO VARCHAR(20),
    MARCA VARCHAR(20),
    PRECIO DECIMAL(10,2),
    -- VALORES VIEJOS
    NOMBRE_BEBIDA_OLD VARCHAR(20),
    TIPO_OLD VARCHAR(20),
    MARCA_OLD VARCHAR(20),
    PRECIO_OLD DECIMAL(10,2),
    -- VALORES VIEJOS
    -- CAMPOS DE COMTROL
    USUARIO VARCHAR(50),
    FECHA DATETIME,
    MOVIMIENTO VARCHAR(20),
    PRIMARY KEY (ID_BITACORA)
    
);


-- TABLA DE RESPALDO DE BEBIDAS
-- sirve para crear una nueva tabla vacía (BEBIDAS_RESPALDO) usando la misma estructura (definición) de otra tabla existente (BEBIDAS).
CREATE TABLE BEBIDAS_RESPALDO LIKE BEBIDAS;
-- Altere la tabla para agregar dos campos mas
ALTER TABLE BEBIDAS_RESPALDO
	ADD COLUMN FECHA_RESPALDO DATETIME,
    ADD COLUMN ACCION VARCHAR(10);
    
-- Altere la tabla para agregar una columna de autoincremento como clave primaria unica para el respaldo unico
ALTER TABLE BEBIDAS_RESPALDO DROP PRIMARY KEY;
ALTER TABLE BEBIDAS_RESPALDO ADD COLUMN ID_RESPALDO INT AUTO_INCREMENT PRIMARY KEY FIRST;

DROP TABLE BEBIDAS_RESPALDO;
-- -- TABLA DE RESPALDO DE BEBIDAS DEFINITIVO
CREATE TABLE BEBIDAS_RESPALDO (
	ID_RESPALDO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ID_BEBIDA INT NOT NULL,
    NOMBRE_BEBIDA VARCHAR(20),
    TIPO VARCHAR(20),
    MARCA VARCHAR(20),
    PRECIO DECIMAL(10,2),
    ID_PROVEEDOR INT,
    FECHA_RESPALDO DATETIME,
    ACCION VARCHAR(10)
);
-- -----------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- CREACION DE LOS TRIGGERS
DROP TRIGGER TRG_INSERT_BEBIDAS;
DELIMITER //

CREATE TRIGGER TRG_INSERT_BEBIDAS
AFTER INSERT ON BEBIDAS
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA_BEBIDAS(
        NOMBRE_BEBIDA, TIPO, MARCA, PRECIO,
        NOMBRE_BEBIDA_OLD, TIPO_OLD, MARCA_OLD, PRECIO_OLD,
        USUARIO, FECHA, MOVIMIENTO
    )
    VALUES (
        NEW.NOMBRE_BEBIDA, NEW.TIPO, NEW.MARCA, NEW.PRECIO,
        NULL, NULL, NULL, NULL,
        USER(), NOW(), 'INSERT'
    );
END//

DELIMITER ;

SELECT * FROM BITACORA_BEBIDAS;
SELECT * FROM BEBIDAS;
INSERT INTO BEBIDAS (NOMBRE_BEBIDA, TIPO, MARCA, PRECIO, ID_PROVEEDOR) VALUES
('Coca Cola', 'Refresco', 'Coca Cola', 15.00, 1),
('Agua Mineral', 'Agua', 'Bonafont', 10.50, 2),
('Jugo Natural', 'Jugo', 'Del Valle', 20.00, 3),
('Cerveza Lager', 'Cerveza', 'Corona', 18.00, 4),
('Vino Tinto', 'Vino', 'Concha y Toro', 150.00, 5);


-- ------------------------------------------------------------------
DROP TRIGGER TRG_INSERT_BEBIDAS;
DELIMITER //

CREATE TRIGGER TRG_UPDATE_BEBIDAS
AFTER UPDATE ON BEBIDAS
FOR EACH ROW  -- CADA QUE AYA ALGUN CAMBIO
BEGIN
    -- Insertar en bitácora sin manejar ID manualmente
    INSERT INTO BITACORA_BEBIDAS(
        NOMBRE_BEBIDA, TIPO, MARCA, PRECIO,
        NOMBRE_BEBIDA_OLD, TIPO_OLD, MARCA_OLD, PRECIO_OLD,
        USUARIO, FECHA, MOVIMIENTO
    )
    VALUES (
        NEW.NOMBRE_BEBIDA, NEW.TIPO, NEW.MARCA, NEW.PRECIO,
        OLD.NOMBRE_BEBIDA, OLD.TIPO, OLD.MARCA, OLD.PRECIO, 
        USER(), NOW(), 'UPDATE'
    );

END//

DELIMITER ;
UPDATE BEBIDAS SET PRECIO = 15.50 WHERE ID_BEBIDA = 3;
SELECT * FROM BITACORA_BEBIDAS;
SELECT * FROM BEBIDAS;
DROP TRIGGER TRG_UPDATE_BEBIDAS;
------------------------------------------------------------------
DELIMITER //

CREATE TRIGGER TRG_DELETE_BEBIDAS
AFTER DELETE ON BEBIDAS
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA_BEBIDAS(
        NOMBRE_BEBIDA, TIPO, MARCA, PRECIO,
        NOMBRE_BEBIDA_OLD, TIPO_OLD, MARCA_OLD, PRECIO_OLD,
        USUARIO, FECHA, MOVIMIENTO
    )
    VALUES (
        NULL, NULL, NULL, NULL,
        OLD.NOMBRE_BEBIDA, OLD.TIPO, OLD.MARCA, OLD.PRECIO, 
        USER(), NOW(), 'DELETE'
    );
END//

DELIMITER ;
DELETE FROM BEBIDAS WHERE ID_BEBIDA = 1;
SELECT * FROM BITACORA_BEBIDAS;
SELECT * FROM BEBIDAS;
DROP TRIGGER TRG_DELETE_BEBIDAS;
-- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
DROP PROCEDURE PS_RESPALDO_BEBIDA
DELIMITER //
CREATE PROCEDURE PS_RESPALDO_BEBIDA (
    IN p_ID_BEBIDA INT,
    IN p_NOMBRE_BEBIDA VARCHAR(20),
    IN p_TIPO VARCHAR(20),
    IN p_MARCA VARCHAR(20),
    IN p_PRECIO DECIMAL(10,2),
    IN p_ID_PROVEEDOR INT,
    IN p_ACCION VARCHAR(10)
)
BEGIN
    INSERT INTO BEBIDAS_RESPALDO (
        ID_BEBIDA, NOMBRE_BEBIDA, TIPO, MARCA, PRECIO, ID_PROVEEDOR, FECHA_RESPALDO, ACCION
    ) VALUES (
        p_ID_BEBIDA, p_NOMBRE_BEBIDA, p_TIPO, p_MARCA, p_PRECIO, p_ID_PROVEEDOR, NOW(), p_ACCION
    );
END//
DELIMITER ;

-- -----------------------------------------------------------------------------------------------
-- RESPALDO INICIAL DE LA TABLA BEBIDAS QUE YA TIENE DATOS.
DROP PROCEDURE PS_RESPALDO_COMPLETO;
DELIMITER //
CREATE PROCEDURE PS_RESPALDO_COMPLETO()
BEGIN
   INSERT INTO BEBIDAS_RESPALDO 
       (ID_BEBIDA, NOMBRE_BEBIDA, TIPO, MARCA, PRECIO, ID_PROVEEDOR, FECHA_RESPALDO, ACCION)
   SELECT 
       ID_BEBIDA, NOMBRE_BEBIDA, TIPO, MARCA, PRECIO, ID_PROVEEDOR, NOW(), 'RESPALDO'
   FROM BEBIDAS;
END//
DELIMITER ;

-- Y ejecutarlo solo una vez con:
CALL PS_RESPALDO_COMPLETO();
-- Trigger para After Insert
DELIMITER //

CREATE TRIGGER TGR_INSERT_RESPALDO_BEBIDA
AFTER INSERT ON BEBIDAS 
FOR EACH ROW
BEGIN
    CALL PS_RESPALDO_BEBIDA(NEW.ID_BEBIDA, NEW.NOMBRE_BEBIDA, NEW.TIPO, NEW.MARCA, NEW.PRECIO, NEW.ID_PROVEEDOR, 'INSERT');
END//

CREATE TRIGGER TRG_UPDATE_RESPALDO_BEBIDA
AFTER UPDATE ON BEBIDAS
FOR EACH ROW
BEGIN
    CALL PS_RESPALDO_BEBIDA(NEW.ID_BEBIDA, NEW.NOMBRE_BEBIDA, NEW.TIPO, NEW.MARCA, NEW.PRECIO, NEW.ID_PROVEEDOR, 'UPDATE');
END;//

CREATE TRIGGER PS_DELETE_RESPALDO_BEBIDA
AFTER DELETE ON BEBIDAS
FOR EACH ROW
BEGIN
    CALL PS_RESPALDO_BEBIDA(OLD.ID_BEBIDA, OLD.NOMBRE_BEBIDA, OLD.TIPO, OLD.MARCA, OLD.PRECIO, OLD.ID_PROVEEDOR, 'DELETE');
END;//

DELIMITER ;
INSERT INTO BEBIDAS (NOMBRE_BEBIDA, TIPO, MARCA, PRECIO, ID_PROVEEDOR) VALUES
('Coca Cola', 'Refresco', 'Coca Cola', 15.00, 1);
UPDATE BEBIDAS SET PRECIO = 20.00 WHERE ID_BEBIDA = 6;
DELETE FROM BEBIDAS WHERE ID_BEBIDA = 2;

DROP TRIGGER TGR_INSERT_RESPALDO_BEBIDA;
SELECT * FROM BITACORA_BEBIDAS;
SELECT * FROM BEBIDAS;
SELECT * FROM BEBIDAS_RESPALDO;
SELECT * FROM BITACORA_BEBIDAS WHERE MOVIMIENTO = 'INSERT';
SELECT * FROM BEBIDAS_RESPALDO WHERE ACCION = 'DELETE';

-- ------------------------------------------------------------------------------------------------------------------------------------------------------------------------

CREATE OR REPLACE VIEW VISTA_INFO_BEBIDA AS
SELECT 
    b.ID_BEBIDA,
    b.NOMBRE_BEBIDA,
    b.TIPO,
    b.MARCA,
    b.PRECIO,
    p.NOMBRE AS NOMBRE_PROVEEDOR,
    p.APELLIDO AS APELLIDO_PROVEEDOR,
    p.TELEFONO AS TELEFONO_PROVEEDOR
FROM 
    BEBIDAS b
INNER JOIN 
    PROVEEDORES p ON b.ID_PROVEEDOR = p.ID_PROVEEDOR;

SELECT * FROM VISTA_INFO_BEBIDA;
DROP VIEW VISTA_INFO_BEBIDA