# Generated by Django 5.2.7 on 2025-10-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('continente', models.CharField(max_length=100)),
                ('idioma', models.CharField(max_length=100)),
                ('habitantes', models.IntegerField()),
                ('gobierno', models.CharField(choices=[('Republica', 'Republica'), ('Monarquia', 'Monarquia')], max_length=50)),
            ],
            options={
                'db_table': 'paises',
            },
        ),
    ]
