# Generated by Django 5.2.7 on 2025-10-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('ciudad', models.CharField(max_length=50)),
                ('puesto', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Empleado',
            },
        ),
    ]
