# Generated by Django 6.0.2 on 2026-02-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Python', 'Python'), ('PHP', 'PHP'), ('Java', 'Java')], max_length=50)),
                ('cupo_maximo', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Curso',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('promedio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cursos', models.ManyToManyField(blank=True, to='api.curso')),
            ],
            options={
                'db_table': 'Estudiante',
            },
        ),
    ]
