# Generated by Django 5.2.7 on 2025-11-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('razon_cita', models.CharField(max_length=50)),
                ('id_cliente', models.IntegerField()),
                ('id_responsable', models.IntegerField()),
                ('id_veterinaria', models.IntegerField()),
            ],
            options={
                'db_table': 'mascotas',
            },
        ),
    ]
